name: Run checks

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
          sudo apt-get install -y zip
          
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: Cache Cppcheck build folder
        id: cache-build
        uses: actions/cache@v4.2.3
        with:
          path: cppcheckFolder
          key: checks
        
      - name: Prepare environment
        if: ${{ steps.cache-build.outputs.cache-hit != 'true' }}  # Only if the cache is not found
        run: |
          mkdir cppcheckFolder
          echo "<?xml version="1"?>
                <platform>
                  <char_bit>8</char_bit>
                  <default-sign>unsigned</default-sign>
                  <sizeof>
                    <short>2</short>
                    <int>4</int>
                    <long>4</long>
                    <long-long>8</long-long>
                    <float>4</float>
                    <double>8</double>
                    <long-double>8</long-double>
                    <pointer>4</pointer>
                    <size_t>4</size_t>
                    <wchar_t>4</wchar_t>
                  </sizeof>
                </platform>" > cppcheckFolder/wii
      
      - name: Build
        run: |
          make all
          echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)" >> "$GITHUB_ENV"
          mkdir -p apps/$(REPO_NAME)
          cp boot.dol apps/$(REPO_NAME)/
          cp hbc/meta.xml apps/$(REPO_NAME)/
          cp -r data/gfx/ apps/$(REPO_NAME)/
          zip -r $(REPO_NAME).zip apps/

      - name: Upload binary
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: ${{ env.REPO_NAME }} Application
          path: ${{ env.REPO_NAME }}.zip
